<template lang="">
  <div class="article">
    <h1 class="main-title">Liquid objects</h1>
    <p>Liquid objects contain attributes to output dynamic content on the page.
      For example, the <code>program</code> object contains an attribute called
      <code>title</code> that can be used to output the title of a program.</p>
    <p>
      <b>Liquid objects</b> are also often referred to as <b>Liquid variables</b>.
    </p>
    <p>
      To output an object's attribute, wrap the object's name in <code>{{</code> and <code>}}</code>, as shown below:
    </p>
    <pre>
      <code class="liquid"  v-el:liqud1>
    {{{'{{ program.title }}'}}}
      </code>
    </pre>
    <hr>
    <h2>Global objects</h2>
    <p>
      The following objects can be used and accessed from <b>any file</b> in your theme,
      and are defined as <b>global objects</b>, or global variables:
    </p>
    <h4>catalog</h4>
    <p>
      This object contains a list of all the programs and categories, in your store.
      <br><a v-link="{ path: '/catalog' }">Reference to object</a>
    </p>
    <h4>current_page</h4>
    <p>
      This object show you current page number.
    </p>
    <h4>elastic_search</h4>
    <p>
      This object contains a list of all the items (programs, posts, pages, authors) matches to your search query.
      <br><a v-link="{ path: '/search' }">Reference to object</a>
    </p>
    <h4>navigation</h4>
    <p>
      This object contains a lists of your left and right navigation items.
      <br><a v-link="{ path: '/nav' }">Reference to object</a>
    </p>
    <h4>request</h4>
    <p>
      This object contains URL params and referer.
      <br><a v-link="{ path: '/nav' }">Reference to object</a>
    </p>
    <h4>settings</h4>
    <p>
      This object contains settings from your <code>settings.json</code> theme file.
      <br><a v-link="{ path: '/settings' }">Reference to object</a>
    </p>
    <h4>slider</h4>
    <p>
      This object contains a list of slides.
      <br><a v-link="{ path: '/settings' }">Reference to object</a>
    </p>
    <h4>store</h4>
    <p>
      This object contains all information about your store and lists of your offers. You can use it with any
      attribute from store object.
      <br><a v-link="{ path: '/store' }">Reference to object</a>
    </p>
    <hr>
    <h2>Other objects</h2>
    <p>
      Some Liquid objects are only used in specific circumstances.
    </p>
    <h4>author</h4>
    <p>
      This object only availible as global inside <code>author.liquid</code>,
      when you open a author page. For example: `/authors/john`.
      You can use it with any attribute from category object.
      <br><a v-link="{ path: '/author' }">Reference to object</a>
    </p>
    <h4>category</h4>
    <p>
      This object only availible as global inside <code>category.liquid</code>,
      when you open a category page. For example: `/categories/my-category`.
      You can use it with any attribute from category object.
      <br><a v-link="{ path: '/category' }">Reference to object</a>
    </p>
    <h4>content_for_layout</h4>
    <p>
      The <code>content_for_layout</code> object is required in <code>theme.liquid</code>.
      It must be placed inside the HTML &lt;body> tag, and it dynamically loads
      content generated by other templates such as <code>index.liquid</code> or <code>program.liquid</code>.
    </p>
    <h4>program</h4>
    <p>
      This object only availible as global inside <code>program.liquid</code>.
      You can use it with any attribute from program object.
      <br><a v-link="{ path: '/program' }">Reference to object</a>
    </p>
    <h4>page</h4>
    <p>
      This object only availible as global inside <code>page.liquid</code>.
      You can use it with any attribute from page object.
      <br><a v-link="{ path: '/page' }">Reference to object</a>
    </p>
  </div>
</template>

<script lang="">
import highlightCode from '../helpers/highlightCode';

export default {
  ready: function initHighlight() {
    highlightCode(this);
  },
};
</script>

<style lang="" scoped>
</style>
